<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AGUI.Client" Version="0.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
		<PackageReference Include="Microsoft.Agents.AI" Version="1.18.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\FoundryAgentsExperiment.Shared\FoundryAgentsExperiment.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\" />
	</ItemGroup>

</Project>
