<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FoundryAgentsExperiment.Agent</RootNamespace>
    <AssemblyName>agent</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.Cosmos" Version="13.5.2" />
    <PackageReference Include="Microsoft.Agents.AI.CosmosNoSql" Version="1.18.0-preview.260818.1" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.18.0" />
    <PackageReference Include="Microsoft.Agents.AI.DevUI" Version="1.18.0-preview.260818.1" />
    <PackageReference Include="Microsoft.Agents.AI.Foundry.Hosting" Version="1.18.0-preview.260818.1" />
    <PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting.AGUI.AspNetCore" Version="1.18.0-preview.260818.1" />
    <PackageReference Include="Microsoft.Agents.AI.Mcp" Version="1.18.0-alpha.260818.1" />
    <PackageReference Include="ModelContextProtocol" Version="[1.4.1]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoundryAgentsExperiment.Shared\FoundryAgentsExperiment.Shared.csproj" />
    <ProjectReference Include="..\FoundryAgentsExperiment.ServiceDefaults\FoundryAgentsExperiment.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
